---
- name: VMs nacheinander starten und auf OS-Bereitschaft warten
  hosts: localhost
  gather_facts: false
  vars:
    # Die Liste kommt idealerweise aus dem AWX Survey
    #target_vms:
    #  - "Server_01"
    #  - "Server_02"

  tasks:
    - name: "Sequenzieller Start-Prozess"
      # Wir nutzen einen Block, um mehrere Schritte pro VM im Loop auszuführen
      include_tasks: start_and_wait_logic.yml
      loop: "{{ target_vms }}"
      loop_control:
        pause: 5 # Optionale Pause von 5 Sek. zwischen den Servern
