---
- name: Mehrere VMs nacheinander hochfahren
  hosts: localhost
  gather_facts: false
  vars:
    # Liste der VMs - kann in AWX über einen Survey überschrieben werden
    target_vms:
      - "WEC03"
      - "WEC02"
      - "WEC01"

  tasks:
    - name: "Schalte VMs ein"
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: false
        name: "{{ item }}"
        state: powered-on  # Schaltet die VM ein
      loop: "{{ target_vms }}"
      register: start_results

    - name: "Warte optional, bis VMware Tools bereit sind"
      community.vmware.vmware_guest_tools_wait:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: false
        name: "{{ item.item }}"
      loop: "{{ start_results.results }}"
      when: item.changed or item.status == 'already_powered_on' # Nur wenn einschalten sinnvoll war
      ignore_errors: yes
